services:
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://127.0.0.1:80/misc/ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - playlog_network
volumes:
  pgadmin_data:
networks:
  playlog_network:
    external: true