DROP TABLE IF EXISTS user_tokens;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles;
DROP TYPE IF EXISTS account_status;