ALTER TABLE games
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE platforms
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE genres
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tags
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE developers
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE publishers
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
