DROP TABLE IF EXISTS game_tags CASCADE;
DROP TABLE IF EXISTS game_platforms CASCADE;
DROP TABLE IF EXISTS game_genres CASCADE;
DROP TABLE IF EXISTS game_publishers CASCADE;
DROP TABLE IF EXISTS game_developers CASCADE;

DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS platforms CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS publishers CASCADE;
DROP TABLE IF EXISTS developers CASCADE;
DROP TABLE IF EXISTS games CASCADE;