services:
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_CONTAINER_URL}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081/status"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - playlog_network
networks:
  playlog_network:
    external: true