services:
  axum-server:
    image: playlog/catalogue-service:latest
    container_name: catalogue-service-axum-server
    build:
      context: ../..
      dockerfile: services/catalogue-service/Dockerfile
      target: final
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH}
    depends_on:
      postgres_catalogue:
        condition: service_healthy
    networks:
      - playlog_network
networks:
  playlog_network:
    external: true